server:
  error:
    include-message: always
    include-binding-errors: always
  port: 1111

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/authandprofile
    username: root
    password: cvsecure
    driverClassName: org.postgresql.Driver

app:
  security:
    # Add jwt-generation token configs
    jwt:
      key-pair:
        private-key: sadfdg7ufidogjsdgo
        public-key: 899udf089u
      access-token:
        signing-algorithm: ES512
        lifespan: 00:05:00
      refresh-token:
        signing-algorithm: ES512
        lifespan: 10:00:00
    integrations:
      # Maybe add life check as permitted endpoint
      # Maybe move root-path to the upper level because I see no purpose in different paths for api and integration requests
      root-path: /integration
      # Move api keys to DB (as there is can be multiple api keys for different clients)
      api-key: asd
  services:
    friends:
      base-url: https://localhost:8081
      timeout: 5000
      api-key: some-api-key
