spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: authandprofile-api
          uri: http://localhost:1111/
          predicates:
            - Path=/api/users/**
        - id: friends-api
          uri: http://localhost:1112/
          predicates:
            - Path=/api/friends/**
        - id: chats-api
          uri: http://localhost:1113/
          predicates:
            - Path=/api/chats/**
        - id: notifications-api
          uri: http://localhost:1114/
          predicates:
            - Path=/api/chats/**

        - id: friends-integration
          uri: http://localhost:1112/
          predicates:
            - Path=/integration/friends/**
        - id: authandprofile-integration
          uri: http://localhost:1111/
          predicates:
            - Path=/integration/users/**
server:
  port: 1110